# Generated by Django 4.2.4 on 2024-08-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_alter_userpreferences_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='currency',
            field=models.CharField(blank=True, default='-------', max_length=250, null=True),
        ),
    ]
